#!/bin/bash
mkdir Tests; 
cd Tests; 
for i in `seq -w 0 10` ; 
do 
	../../../TestProvider/Random.Number.sh 16 | sed 's/-//g' > 13.$i.in; 
	echo $((`../../../TestProvider/Random.Number.sh 2 | sed 's/-//g'` % 55)) >> 13.$i.in; 
	echo $((`../../../TestProvider/Random.Number.sh 1 | sed 's/-//g'` % 2)) >> 13.$i.in; 
	python ../*.py < 13.$i.in > 13.$i.sol ; 
done
