#!/bin/bash
mkdir Tests; 
cd Tests; 
for i in `seq -w 0 2` ; 
do 
	echo "integer" > 09.0$i.in;
	../../../TestProvider/Random.Number.sh 14 >> 09.0$i.in; 
	python ../*.py < 09.0$i.in > 09.0$i.sol ; 
done
for i in `seq -w 3 6` ; 
do 
	echo "real" > 09.0$i.in;
	../../../TestProvider/Random.Decimal.sh 14 3 1 >> 09.0$i.in; 
	python ../*.py < 09.0$i.in > 09.0$i.sol ; 
done
for i in `seq -w 7 10` ; 
do 
	echo "text" > 09.$i.in;
	../../../TestProvider/Random.Number.sh 14 >> 09.$i.in; 
	python ../*.py < 09.$i.in > 09.$i.sol ; 
done
