#!/bin/bash
mkdir Tests; 
cd Tests; 
for i in `seq -w 0 10` ; 
do 
	../../../TestProvider/Random.Decimal.sh 14 3 1 > 04.$i.in; 
	../../../TestProvider/Random.Decimal.sh 14 3 1 >> 04.$i.in; 
	../../../TestProvider/Random.Decimal.sh 14 3 1 >> 04.$i.in; 
	python ../*.py < 04.$i.in > 04.$i.sol ; 
done
