#!/bin/bash
mkdir Tests; 
cd Tests; 
for i in `seq -w 0 9` ; 
do 
	echo $i > 08.0$i.in; 
	python ../*.py < 08.0$i.in > 08.0$i.sol ; 
done
for i in `seq -w 10 11` ; 
do 
	../../../TestProvider/Random.Decimal.sh 14 3 1 > 08.$i.in; 
	python ../*.py < 08.$i.in > 08.$i.sol ; 
done
for i in `seq -w 12 13` ; 
do 
	../../../TestProvider/Random.Number.sh 18 > 08.$i.in; 
	python ../*.py < 08.$i.in > 08.$i.sol ; 
done
for i in `seq -w 14 15` ; 
do 
	../../../TestProvider/Random.String.sh 100 > 08.$i.in; 
	python ../*.py < 08.$i.in > 08.$i.sol ; 
done
