#!/bin/bash
mkdir Tests; 
cd Tests; 
for i in `seq -w 0 10` ; 
do 
	../../../TestProvider/Random.Number.sh 16 | sed 's/-//g' > 15.$i.in; 
	echo $((`../../../TestProvider/Random.Number.sh 2 | sed 's/-//g'` % 16)) >> 15.$i.in; 
	echo $((`../../../TestProvider/Random.Number.sh 2 | sed 's/-//g'` % 16)) >> 15.$i.in; 
	echo $((`../../../TestProvider/Random.Number.sh 2 | sed 's/-//g'` % 16)) >> 15.$i.in; 
	python ../*.py < 15.$i.in > 15.$i.sol ; 
done
