#!/bin/bash
mkdir Tests; cd Tests; for i in `seq -w 0 10` ; do ../../../TestProvider/Random.Word.sh 1000 > 02.$i.in; echo -n " " >> 02.$i.in ; ../../../TestProvider/Random.Word.sh 1000 >> 02.$i.in; python ../*.py < 02.$i.in > 02.$i.sol ; done
