#!/bin/bash
mkdir Tests; 
cd Tests; 
for i in `seq -w 0 10` ; 
do 
	../../../TestProvider/Random.Digit.sh -n > 06.$i.in; 
	../../../TestProvider/Random.Digit.sh -n >> 06.$i.in; 
	../../../TestProvider/Random.Digit.sh -n >> 06.$i.in; 
	../../../TestProvider/Random.Digit.sh >> 06.$i.in; 
	python ../*.py < 06.$i.in > 06.$i.sol ; 
done
